<template>
	<div class="container">
		<h1>Thông Tin Thêm Về Bạn</h1>
		<div class="row">
			<div class="col-sm-6">
				<h3>Hình Dáng</h3>
				<div class="form-group">
					<label for="sel1">Select list (select one):</label>
					<select class="form-control" id="sel1">
						<option>-</option>
						<option>Vừa Phải</option>
						<option>Thể Thao</option>
						<option>Mảnh Mai</option>
					</select>
				</div>	
			</div>

			<div class="col-sm-6">
				<h3>Hình Dáng</h3>
				<div class="form-group">
					<label for="sel1">Select list (select one):</label>
					<select class="form-control" id="sel1">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
					</select>
				</div>
			</div>
			<div class="col-sm-6">

			</div>
		</div>
	</div>
	
</template>
<script>
	
</script>
